- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 1800
  become: true

- name: Install Apache
  apt:
    name: apache2
    state: present
  become: true

- name: Ensure web root exists
  file:
    path: /var/www/html
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Deploy index.html showing FQDN
  copy:
    content: "{{ ansible_facts['fqdn'] }}\n"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0444"
  notify: restart apache
  become: true

- name: Ensure apache is enabled and running
  service:
    name: apache2
    state: started
    enabled: true
  become: true

